apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devopscc
  region: eu-central-1
nodeGroups:
  - name: ng1
    desiredCapacity: 1
    instanceType: t2.micro
    ssh:
      publicKeyName: aws-eks 
  - name: ng2
    desiredCapacity: 1
    instanceType: t2.small
    ssh:
      publicKeyName: aws-eks