apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app:  php
    spec:
      containers:
        - name:  php
          image: hnom/devopscc_webserver:latest
          ports:
           - containerPort: 80
             name:  php

---
apiVersion: v1
kind: Service
metadata:
  name:  phpservice
spec:
  selector:
    app: php
  ports:
   - protocol: TCP
     port:  80
     targetPort: 80
     nodePort: 30080
  type:  LoadBalancer