version: '3.3'
services:
  mysql-db:
    image: mysql:5.7.36
    environment:
      - MYSQL_DATABASE=joomla-db
    env_file:
      - .env/mysql.env    
    container_name: mysql-db
    hostname: mysql-db
    ports:
      - 3306:3306
    networks:
      - mysql-net
    volumes:
      - webs-mysql-db:/var/lib/mysql:rw
  pma:
    image:  phpmyadmin:5.1.1-apache
    environment:
      - PMA_HOST=mysql-db
    env_file:
      - .env/pma.env
    container_name: pma
    hostname: pma
    ports:
      - 85:80
    networks:
      - mysql-net
  joomla:
    image: joomla:4.0.5-apache
    environment:
      - JOOMLA_DB_HOST=mysql-db
    env_file:
      - .env/joomla.env
#    build:
#      context:
#      dockerfile: 
#      cache_from:
#      args:
#        buildno:
#        gitcommithash:
#      labels:
#        - 
#      network:
    container_name: joomla
    hostname: joomla
    depends_on:
      - mysql-db
      - pma
    ports:
      - 80:80
    networks:
      - mysql-net    
    volumes:
      - webs-joomla-scode:/var/www/html:rw
networks:
  mysql-net:
volumes:
  webs-mysql-db:
  webs-joomla-scode: