# Config for UI deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uideployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app:  ui
    spec:
      containers:
        - name:  ui
          image: hnom/codearena-ui:latest
          ports:
           - containerPort: 80
             name:  ui

---
# Config for UI service
apiVersion: v1
kind: Service
metadata:
  name:  uiservice
spec:
  selector:
    app: ui
  ports:
   - protocol: TCP
     port:  80
     targetPort: 8080
     nodePort: 30084
  type:  LoadBalancer