version: '3.7'
services:
  jenkins:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    image: 'fomindn/jenkins:lts'
    container_name: 'jenkins'
    hostname: jenkins
    networks:
      - jenkins-net
    ports:
      - 50000:50000
      - 8080:8080
#    environment:
#      - DOCKER_HOST=tcp://docker:2376
#      - DOCKER_CERT_PATH=/certs/client
#      - DOCKER_TLS_VERIFY=1
    volumes:
#      - 'jenkins-docker-certs:/certs/client:ro'
      - 'jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
#    depends_on:
#      - docker
#  docker:
#    image: 'docker:dind'
#    privileged: true
#    container_name: 'docker'
#    hostname: docker
#    networks:
#      - jenkins-net
#    ports:
#      - 2376:2376
#    environment:
#      - 'DOCKER_TLS_CERTDIR=/certs'
#    volumes:
#      - 'jenkins-docker-certs:/certs/client'
#      - 'jenkins-data:/var/jenkins_home'
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    command: --storage-driver=overlay2
  ngrok:
    image: 'ngrok/ngrok:latest'
    container_name: 'ngrok'
    hostname: ngrok
    networks:
      - jenkins-net
    env_file:
      - ../ngrok/.env/ngrok.env
    ports:
      - 4040:4040
    command: 'http jenkins:8080'
    depends_on:
      - jenkins
#      - docker
volumes:
#  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins-net:
