version: '3.3'
services:
  mysql-db:
    build:
      context: '.'
      dockerfile: 'Dockerfiles/Dockerfile.mysql'
    image: fomindn/mysql:5.7.36
    environment:
      - MYSQL_DATABASE=joomla-db
    env_file:
      - .env/mysql.env    
    container_name: mysql-db
    hostname: mysql-db
    ports:
      - 3306:3306
    networks:
      - mysql-net
    volumes:
      - webs-mysql-db:/var/lib/mysql:rw
  pma:
    build:
      context: '.'
      dockerfile: 'Dockerfiles/Dockerfile.pma'
    image:  fomindn/pma:5.1.1
    environment:
      - PMA_HOST=mysql-db
    env_file:
      - .env/pma.env
    container_name: pma
    hostname: pma
    ports:
      - 85:80
    networks:
      - mysql-net
  joomla:
    build:
      context: '.'
      dockerfile: 'Dockerfiles/Dockerfile.joomla'
    image: fomindn/joomla:4.0.5
    environment:
      - JOOMLA_DB_HOST=mysql-db
    env_file:
      - .env/joomla.env
    container_name: joomla
    hostname: joomla
    depends_on:
      - mysql-db
      - pma
    ports:
      - 80:80
    networks:
      - mysql-net    
    volumes:
      - webs-joomla-scode:/var/www/html:rw
networks:
  mysql-net:
volumes:
  webs-mysql-db:
  webs-joomla-scode:
