apiVersion: apps/v1
# What will be doing? Deployment
kind: Deployment
metadata:
  # The name of deployment
  name: mysql-deployment
  labels:
    app: mysql
# Specification for deployment
spec:
  # How many REPLICAS of the PODS will be creating
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  ### Blueprint for the PODS
  template:
    metadata:
      labels:
        app: mysql
    # Specification for a pod
    spec:
      containers:
      - name: mysql-db
        image: fomindn/mysql:5.7.36
        resources:
        ports:
          - containerPort: 3306
  ### END Blueprint
