apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
# Тип секрета
# https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
type: Opaque
data:
  mysql-root-pass: cGFzcw==
  mysql-user-name: am9vbWxh
  mysql-user-pass: am9vbWxh
  mysql-db-name: am9vbWxhLWRi
